package lk.ijse.gdse.Util;

public enum  TextField {

    ID,INQUIRYID,ACCOUNTID,BALANCEID,EMPLOYEEID,INTERESTRATEID,LOANID,PAYMENTID,REMINDERID,NAME,EMAIL,CONTACT,ADDRESS,AGE,BIRTH,NIC,SALARY,DATE,AMOUNT,PERCENTAGE,TERM;
}
